### ISSUE TITLE
【翻译】-16个有用的CSS技巧

### ISSUE THREAD

**Issue by bytemofan** [Mmzer/think#7]
![image](https://cloud.githubusercontent.com/assets/9158841/22091872/9d34d170-de34-11e6-9e0a-9f2406720a55.png)

## CSS 专业技巧

[原文](https://github.com/AllThingsSmitty/css-protips)

一个帮助你提高css技巧的tips集合
> 对于其他非常好的清单请查看[@sindresorhus](https://github.com/sindresorhus/)创建的清单[awesome lists](https://github.com/sindresorhus/awesome/)

### 使用CSS reset
CSS reset能够帮助你统一不同浏览器的初始化样式，使得你的浏览器环境就像白板一样干净！你可以使用CSS reset库[ Normalize](http://necolas.github.io/normalize.css/)，也可以使用一个更简化的复位方法：

```css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
```
这样所有元素的`margin`和`padding`都被剥离重置，并且使用`box-sizing`使得你可以使用CSS盒模型来管理你的布局。

[Demo](http://codepen.io/AllThingsSmitty/pen/kkrkLL)

*Note*: 如果你参考下边的技巧*继承 box-sizing*，你可能不会在复位CSS中使用box-sizing

### 继承`box-sizing`
让`box-sizing`属性继承自`html`:
```css
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```
这使得你可以在插件或者组件中更容易的改变元素的`box-sizing`的行为。

### 使用`:not()`来决定表单是否使用边框
与其加上边框:
```css
/* add border */
.nav li {
  border-right: 1px solid #666;
}
```
然后去掉最后一个元素的边框：
```css
/* remove border */
.nav li:last-child {
  border-right: none;
}
```
不如使用伪类选择器`:not()`来达成想要的效果：
```css
.nav li:not(:last-child) {
  border-right: 1px solid #666;
}
```
当然，你也可以使用`.nav li + li`或者`.nav li:first-child ~ li`来达成，但`:not()`选择器的方式更清晰明了，一目了然！

[Demo](http://codepen.io/AllThingsSmitty/pen/LkymvO)

### 为body添加行高`line-height`
你不需要去为每一个元素如`<p>`、`<h*>`一一添加行高，你只需要在body上添加就够了！
```css
body {
  line-height: 1.5;
}
```
这样文本元素可以很容易地从`body`中继承。

[Demo](http://codepen.io/AllThingsSmitty/pen/VjbdYd)

### 垂直居中任何元素
这不是黑魔法，实际上你真的可以居中任何元素：
```css
html, body {
  height: 100%;
  margin: 0;
}

body {
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
  display: -webkit-flex;
  display: flex;
}
```
这还不够？水平居中，垂直居中...任何元素，任何时间，任何地方？CSS-Tricks有一篇[好文章](https://css-tricks.com/centering-css-complete-guide/)讲到了各种居中的技巧。

*Node*：注意flexbox在IE11下有一些bug。

[Demo](http://codepen.io/AllThingsSmitty/pen/GqmGqZ)

### 逗号分隔的列表
确保列表的每一项都是用逗号来分隔：
```css
ul > li:not(:last-child)::after {
  content: ",";
}
```
使用`:not()`伪类去掉最后一项的逗号。

*Note*：这个技巧对于无障碍屏幕阅读器，对于从浏览器复制/粘贴css生成的不兼容代码，得小心行事！

### 使用负的`nth-child`来选择元素
使用负的选择器`nth-child`来选择1~n个元素。
```css
li {
  display: none;
}

/* select items 1 through 3 and display them */
li:nth-child(-n+3) {
  display: block;
}
```
或许你已经学会了如何去使用`:not()`，试试这个：
```css
/* select items 1 through 3 and display them */
li:not(:nth-child(-n+3)) {
  display: none;
}
```
看吧，这非常容易！

[Demo](http://codepen.io/AllThingsSmitty/pen/WxjKZp)

### 使用SVG图标
没有理由不使用SVG图标：
```css
.logo {
  background: url("logo.svg");
}
```
SVG在所有分辨率类型的设备下缩放良好，并且IE9+以及其它浏览器也都缩放良好。所以，放弃使用.png、.jpg、.gif等等其它图片格式的图标吧！

*Note*：对于只有图标的按钮，如果SVG文件没有加载成功，这个样式将能帮助保持可访问性：
```css
.no-svg .icon-only:after {
  content: attr(aria-label);
}
```

### 使用“形似猫头鹰”的选择器
它可能有一个奇怪的名字，但使用通用选择器（*）与兄弟选择器（+）组合使用时可以提供一个强大的CSS能力：
```css
* + * {
  margin-top: 1.5em;
}
```
在此示例中，遵循其他元素的文档流中的所有元素将都接收上边距 margin-top: 1.5em 的样式。

关于更多的“形似猫头鹰”选择器的东西，可以阅读[Heydon Pickering's的文章](http://alistapart.com/article/axiomatic-css-and-lobotomized-owls)

[Demo](http://codepen.io/AllThingsSmitty/pen/grRvWq)

### 使用`max-height`来创建纯CSS的滑块
使用`max-height`和`overflow-hidden`来实现纯CSS滑块：
```css
.slider {
  max-height: 200px;
  overflow-y: hidden;
  width: 300px;
}

.slider:hover {
  max-height: 600px;
  overflow-y: scroll;
}
```
移入滑块元素时增大它的 max-height 的值，便可以显示溢出部分。

### 等宽单元格
Tables布局可能是一个痛苦的工作，所以试着去使用`table-layout:fixed`去使每一个单元格等宽。
```css
.calendar{
      table-layout:fixed;
}
```
无痛的表格布局。
[Demo](http://codepen.io/AllThingsSmitty/pen/jALALm)

### 使用flexbox来清除多余的外边距
与其使用 nth-， first-， 和 last-child 去除列之间多余的间隙，不如使用 flexbox 的 space-between 属性：
```css
.list {
  display: flex;
  justify-content: space-between;
}

.list .person {
  flex-basis: 23%;
}
```
这样列之间的间隙相等，且首尾没有间隙。

### 使用属性选择器选择空链接
当一个`<a>`元素没有文本节点，但有href值时，显示它的href值：
```css
a[href^="http"]:empty::before {
  content: attr(href);
}
```
这是很方便的！
[Demo](http://codepen.io/AllThingsSmitty/pen/zBzXRx)

### “预设”链接样式
给“预设”链接一个样式：
```css
a[href]:not([class]) {
  color: #008000;
  text-decoration: underline;
}
```
通过 CMS 系统插入的链接，通常没有 class 属性，以上样式可以甄别它们，而且不会影响其它样式。

### 一致的垂直节奏
为内部子元素使用通配符去创建一个一致的垂直节奏。
```css
.intro > * {
  margin-bottom: 1.25rem;
}
```
一致的垂直节奏可以提供视觉美感，使内容更可读。

### 内在比例盒子
要创建一个具有内部比例的盒子，你需要去填充一个div的顶部和底部padding。
```css
.container {
  height: 0;
  padding-bottom: 20%;
  position: relative;
}
.container div {
  border: 2px dashed #ddd;
  height: 100%;
  left: 0;
  position: absolute;
  top: 0;
  width: 100%;
}
```
使用20％的填充使得框等于其宽度的20％的高度。不管视口的宽度，子元素的div将保持其宽高比（100％/ 20％= 5:1）。
[Demo](http://codepen.io/AllThingsSmitty/pen/jALZvE)

### 定义加载失败图像的样式
只要一点点CSS就可以美化破碎图片：
```css
img {
  display: block;
  font-family: Helvetica, Arial, sans-serif;
  font-weight: 300;
  height: auto;
  line-height: 2;
  position: relative;
  text-align: center;
  width: 100%;
}
```
然后添加伪元素的样式，显示使用者信息和加载失败图像的URL：
```css
img:before {
  content: "We're sorry, the image below is broken :(";
  display: block;
  margin-bottom: 10px;
}

img:after {
  content: "(url: " attr(src) ")";
  display: block;
  font-size: 12px;
}
```
了解更多关于这类样式的技巧 [Ire Aderinokun](https://github.com/ireade/)的 [原帖](http://bitsofco.de/styling-broken-images/)。

### 使用`rem`作为全局的尺寸；使用`em`作为局部的尺寸
在根元素设置了基本的字体尺寸（html{font-size:100%}）之后，设置文本元素的字体尺寸用`em`:
```css
h2 {
  font-size: 2em;
}
p {
  font-size: 1em;
}
```
然后用`rem`设置模块的字体大小。
```css
article {
  font-size: 1.25rem;
}

aside .module {
  font-size: .9rem;
}
```
现在，每个模块划分清晰，是的编写样式更容易、灵活，便于维护。

### 隐藏没有静音、自动播放的影片
这是一个提高用户体验的很好的技巧。避免在加载页面时自动播放视频，且不是静音状态时，则不显示视频：
```css
video[autoplay]:not([muted]) {
  display: none;
}
```
再一次，我们利用了`:not()`伪类。

### 使用`:root`伪类来实现弹性字体
响应式布局的字体大小应该随着视口的尺寸变化。你可以使用`:root`根据视口的宽高计算字体的大小：
```css
:root {
  font-size: calc(1vw + 1vh + .5vmin);
}
```
然后，你可以利用`rem`来设置字体大小，这里`rem`的值就是有`:root`计算得来的。
```
body {
  font: 1rem/1.6 sans-serif;
}
```
[Demo](http://codepen.io/AllThingsSmitty/pen/XKgOkR)

### 为表单元素设置`font-size`以获得更好的移动端体验
为了避免表单元素（`<select>`下拉框点击出现下拉框）在移动端浏览器（iOS Safari等等）下缩放，我们需要给表单元素添加一个`font-size`样式：
```css
input[type="text"],
input[type="number"],
select,
textarea {
  font-size: 16px;
}
```

### 浏览器支持情况
这些技巧适用于最新版的 Chrome, Firefox, Safari, Opera, Edge, 以及 IE11。
