### ISSUE TITLE
【翻译】--CSS居中:完全指南

### ISSUE THREAD

**Issue by bytemofan** [Mmzer/think#8]
[原文](https://css-tricks.com/centering-css-complete-guide/)
[作者:Chris Coyier](https://css-tricks.com/author/chriscoyier/)

css居中很难吗？显然不是。我认为这个问题并不是很难，但是它有很多种实现方法，难点是需要知道在什么场合使用什么样的居中方式！

因此，我制作了一棵决策树去帮助你更容易的去解决这个问题。

我们太需要居中了......

### 内联元素水平居中
在一个块级元素内部水平居中内联元素，我们只需要这样做：
```css
.center-children {
  text-align: center;
}
```
[Demo](http://codepen.io/chriscoyier/pen/HulzB)

这种方式对于inline、inline-block、inline-table和inline-flex等都能起作用。

### 块级元素水平居中
你可以设置一个块级元素的`margin-left`和`margin-right`的值为`auto`来实现水平居中（块级元素的宽度必须是固定值，否则它将充满父元素从而达不到居中效果）：
```css
.center-me {
  margin: 0 auto;
}
```
[Demo](http://codepen.io/chriscoyier/pen/eszon)

不管你居中的是定宽的块级元素或父级元素，它都能工作。

【注意】你不能使用这种方式居中`float`元素。参考这个[技巧](http://css-tricks.com/float-center/)

### 多个块级元素水平居中
如果你需要将两个或两个以上的块级元素在一行上水平居中显示，你可以通过设置不同的`display`的值来实现，例如这个[例子](http://codepen.io/chriscoyier/pen/ebing)，你可以设置为`inline-block`和flexbox的方式来居中对齐。
```css
.inline-block-center {
  text-align: center;
}
.inline-block-center div {
  display: inline-block;
  text-align: left;
}

.flex-center {
  display: flex;
  justify-content: center;
}
```
如果你是想实现多个块级元素堆积在彼此的顶部还居中显示的话，可以考虑使用自动计算margin的方式：
```css
main {
  background: white;
  margin: 20px 0;
  padding: 10px;
}

main div {
  background: black;
  margin: 0 auto;
  color: white;
  padding: 15px;
  margin: 5px auto;
}

main div:nth-child(1) {
  width: 200px;
}
main div:nth-child(2) {
  width: 400px;
}
main div:nth-child(3) {
  width: 125px;
}
```
[完整Demo](http://codepen.io/chriscoyier/pen/haCGt)

## 垂直居中
使用css垂直居中有一点点麻烦：

#### 单行内联元素
有些时候，内联/文本元素表现为垂直居中，仅仅是因为他们的上面和下面有着相同的padding值：
```css
.link {
  padding-top: 30px;
  padding-bottom: 30px;
}
```
[Demo](http://codepen.io/chriscoyier/pen/ldcwq)

如果padding属性因为某些原因不能使用，并且你还需要试图去居中一些不会换行的文本元素时，你可以设置`line-height`的值等于文本元素的高度去实现垂直居中：
```css
.center-text-trick {
  height: 100px;
  line-height: 100px;
  white-space: nowrap;
}
```
[Demo](http://codepen.io/chriscoyier/pen/LxHmK)

#### 多行内联元素
设置上下相等的padding值同样可以提供多行文本框的垂直居中效果，但如果它不起效，可以通过css为文本设置一个表现类似`table-cell`的父级容器，然后在使用[`vertical-align`](http://css-tricks.com/almanac/properties/v/vertical-align/)属性调整文本的的行内对齐方式来实现垂直居中效果：
```css
.center-table {
  display: table;
  height: 250px;
  background: white;
  width: 240px;
  margin: 20px;
}
.center-table p {
  display: table-cell;
  margin: 0;
  background: black;
  color: white;
  padding: 20px;
  border: 10px solid white;
  vertical-align: middle;
}
```
[Demo](http://codepen.io/chriscoyier/pen/ekoFx)

如果table-like形式的布局已经过时了，你可以尝试使用flexbox来垂直居中元素。

一个单独的flex子元素可以很容易的做到在flex父容器中居中：
```css
.flex-center-vertically {
  display: flex;
  justify-content: center;
  flex-direction: column;
  height: 400px;
}
```
[Demo](http://codepen.io/chriscoyier/pen/uHygv)

记住使用这种方式时，父容器必须有一个固定的高度（px，%等等）。

如果以上两种方式都失效了，你可以使用“鬼元素（ghost element）”技术，也就是使用一个高度等于父级元素高度的伪元素，并设置它的`vertical-align`属性值为`middle`，即可实现垂直居中：
```css
.ghost-center {
  position: relative;
}
.ghost-center::before {
  content: " ";
  display: inline-block;
  height: 100%;
  width: 1%;
  vertical-align: middle;
}
.ghost-center p {
  display: inline-block;
  vertical-align: middle;
}
```
[Demo](http://codepen.io/chriscoyier/pen/ofwgD)

#### 已知元素的高度
出于很多原因，网页布局中不知道元素的高度是很常见的：宽度变化，触发文本高度的重绘；字体的变化也可以改变高度值；文字数量的变化也可以改变高度值；具有固定宽高比的元素，比如图片，resize的时候也会改变高度值，等等。

但是如果你知道元素的高度值，你可以这样实现垂直居中：
```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  height: 100px;
  margin-top: -50px; /* account for padding and border if not using box-sizing: border-box; */
}
```
[Demo](http://codepen.io/chriscoyier/pen/HiydJ)

#### 未知元素的高度
实现未知高度的元素的垂直居中任然是可以做到的，我们可以使用浮动定位结合transform的translate属性来使元素位移一段距离实现：
```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}
```
[Demo](http://codepen.io/chriscoyier/pen/lpema)

#### 使用flexbox
没有太大问题，使用flexbox使得实现更容易：
```css
.parent {
  display: flex;
  flex-direction: column;
  justify-content: center;
}
```
[Demo](http://codepen.io/chriscoyier/pen/FqDyi)

## 水平垂直居中
你可以使用以上技术组合实现完美的居中效果，但是我发现可以归纳为三个方面：

### 固定宽高的元素
在使用了`position: absolute`，且设置了元素的`top`和`left`值为`50%`之后，再设置元素的负margin值（上边距和左边距）为元素宽高的一半即可水平垂直居中元素，且具有良好的浏览器支持性：
```css
.parent {
  position: relative;
}

.child {
  width: 300px;
  height: 100px;
  padding: 20px;

  position: absolute;
  top: 50%;
  left: 50%;

  margin: -70px 0 0 -170px;
}
```
[Demo](http://codepen.io/chriscoyier/pen/JGofm)

### 未知宽高的元素
如果不知道元素的宽和高，你可以使用设置`transform`属性偏移对应方向上的距离等于负50%（基于当前元素的宽和高）的方式来居中：
```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```
[Demo](http://codepen.io/chriscoyier/pen/lgFiq)

### 使用flexbox
为了使两个方向上的flex元素居中，你需要使用两个居中元素：
```css
.parent {
  display: flex;
  justify-content: center;
  align-items: center;
}
```
[Demo](http://codepen.io/chriscoyier/pen/msItD)

## 结论

你能使用css居中任何元素。
